### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by adrian-jaques-b** [yguo0102/transformer_dapt_sapt_tapt#1]
Hello,

I really appreciate that you are sharing your code. I find you approach very interesting!
However, I was trying to run your code and I'm having some issues with the python version. So I wanted to ask which version you are using?

Thank you so much!
Kind regards,
Jaqu

**Comment by yguo0102** [comment]
> 



> Hello,
> 
> I really appreciate that you are sharing your code. I find you approach very interesting! However, I was trying to run your code and I'm having some issues with the python version. So I wanted to ask which version you are using?
> 
> Thank you so much! Kind regards, Jaqu

The code was developed with Python 3.7.7.

**Comment by adrian-jaques-b** [comment]
Thank you for your fast reply! :)
